.gitignore, .travis.yml, lib/juice.js, lib/selector.js, lib/utils.js, package.json, test/cases/identical-important.out, test/cases/jsdom.out, test/cases/juice-content/width-attr.out, test/cases/regression-media.out, test/html/no_css.out.html, test/juice.test.js, test/run.js, test/test.js
@rauchg This contains #98
- supports node 0.12 and fixes #99 
- removes jsdom completely in favor of cheerio which allows inlining document fragments correctly and likely improves performance per #80 
- adds code coverage info
Breakage:
Because jsdom was exposed with inlineDocument, that method now uses a cheerio document. I can't imagine that was a very popular feature though and I don't think preserving that interface is justified since cheerio does a better job of doing what juice is supposed to do, which is just inline documents.
Note, readme need some updating at the moment
=> Cheerio node 12

.travis.yml, lib/juice.js, lib/selector.js, lib/utils.js, package.json, test/cases/identical-important.out, test/cases/jsdom.out, test/cases/regression-media.out, test/run.js, test/test.js
@rauchg really sorry this PR is so large, but it removes all of the code that was inlining external resources and cleans up whatever was along the way. From what I can figure, juice used to use grunt-inline, which is kind of a mess, so based on that I wrote a new resource inliner that is at https://www.npmjs.com/package/web-resource-inliner and is a straight node library instead of a grunt task.
The only big breaking change here is that I removed the overloaded `juice.juice()` call so someone would now be required to use `juiceFile`, `juiceDocument` or `juiceContent` for example. These all have a callback as the last argument, which keeps things standard and is with node convention.
I simplified/standardized the test runners, as they had become a mess, the same tests are all there, but …
=> Move resource inlining to external library

README.md, lib/juice.js, test/run.js
- Updated docs as needed for current master, refers to cheerio instead of jsdom, updated all signatures, worked to make docs more consistently formatted
- Removed unused options
- Reverted signature on `inlineContent` based on my reading the docs, it was previously stated that it just uses the provided CSS string, so getting resources didn't make sense as it would change the stated intended behavior of the method.
- Proposing the name `juiceContent` be changed to `juiceResources` - to make it clearer it fetches remote resources and to distinguish that `juiceContent` isn't a mirror of `inlineContent` as the names were confusing to me. As long as the interface is changing, this would be the time to do this if we want to. Otherwise I can revert it.
@rauchg @parshap
=> update docs, revert signature on inlineContent

README.md, lib/juice.js, test/cases/juice-content/table-attr.html, test/cases/juice-content/table-attr.json, test/cases/juice-content/table-attr.out
Adding an option to add style attributes on the table elements on top of the already inlined styles. This is required for certain email clients. This commit adds attributes for background-color, background-image, vertical-align and text-align to table elements.
=> Adding support for table style attributes

lib/juice.js, package.json, test/juice.test.js, test/run.js, test/test.js
fixes #137 
Fixes the error and adds a test case that uses `inlineContent` now which should prevent regression.
Also, some more linting in here, tests were not updated to be `use_strict` compliant on the last CL.
=> fix undefined options

package.json
This PR adds the license to the package file and updates `web-resource-inliner` so it uses the latest version which doesn't use the vulnerable version of `uglify-js`. The new version of `web-resource-inliner` has a PR already created jrit/web-resource-inliner#8 and this is being done in response to this advisory: https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons
=> Update web-resource-inliner to the latest version, add license to package file

lib/juice.js, test/cases/juice-content/pseudo-elements-and-width-attr.html, test/cases/juice-content/pseudo-elements-and-width-attr.json, test/cases/juice-content/pseudo-elements-and-width-attr.out
The element object is currently referencing a jQuery object that wraps the created pseudo element, but the rest of the code expects to be working with raw dom element objects.
This change fixes it by calling `.get(0)` on the created jQuery object so it becomes a normal dom element object.
=> Fix bug with reference to pseudo element object

lib/juice.js, test/cases/juice-content/width-attr.html, test/cases/juice-content/width-attr.out
Mapping percentages width attributes in table elements is useful for fluid layouts and does not break any specs.
=> Enabled percentages for tableElements on 'applyWidthAttributes' option.

README.md, lib/juice.js, test/cases/juice-content/embed.css, test/cases/juice-content/embed.html, test/cases/juice-content/embed.json, test/cases/juice-content/embed.out
This attribute is intended for use on `<link>` tags.
When the <link> is inlined the styles in the <style> will not be inlined and the tag will not be removed.
This fixes #164 and replaces #129
=> Implement a `data-embed` attribute.

History.md, README.md, lib/client.js, lib/juice.js, lib/property.js, lib/utils.js
Sort of fixes #38 
Thanks @barretts for your research on this. This diff is huge because it keeps the existing API with no test changes, but makes `juice/client` able to be browserified with the compatible subset of features. It is just a giant refactoring.
=> Refactor to provide browser support at juice/client

client.js, index.js, package.json
The readme documents using `require("juice/client")` for client-side (browser) use, but this file doesn't exist and the `require()` results in an error.
The following changes were made:
1. Move client entry-point from `lib/client.js` to `client.js`.
2. Move server entry-point from `lib/juice.js` to `index.js`, all entry-points are in the package's root.
3. Add "browser" field to `package.json` so that `require("juice")` resolves to `client.js` when using browserify and webpack.
=> Fix require("juice/client")

lib/selector.js, lib/utils.js, package.json, test/cases/juice-content/pseudo-elements.html, test/cases/juice-content/pseudo-elements.out, test/juice.test.js
- Deprecates `utils.toArray()` which is not used internally and is essentially useless as an external API
- Adds test coverage for `toString()` which is also not used internally, but looks like it could be useful externally
- Fixes specificity for `:not()` selectors, in particular that slick was not being used correctly so `:not()` was previously never found. This change is semver-minor.
=> Addressing paths without test coverage

History.md, README.md, bin/juice, lib/cli.js, package.json, test/cli.js
CLI supports all juice options as well as supporting loading options from a JSON file. CLI tests also pass on Windows finally.
Replaces #126 and #174 
/cc @niek
=> CLI refresh

README.md
I discovered that juiceDocument doesn't work as documented.   Have updated documentation to match implementation.
=> fix README: juiceDocument doesn't return a string

client.js
As mentioned in #162 there's still an issue with calling toUpperCase() on an undefined property. Fixed here.
=> fixed undefined property error #162

README.md, client.js, test/juice.test.js
It happens in some projects that I had the necessity to not inline some properties, usually for email templates.
For instance:
<pre>* {
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
}</pre>
With this commit I added another global variable, `juiceClient.excludedProperties`, in which the user can specify the properties that he doesn't want to inline.
For instance:
<pre>[
'-webkit-font-smoothing',
'-moz-osx-font-smoothing'
]</pre>
Can it be useful?
Cheers,
Raffaele
=> Add a functionality to exclude css properties from inliner

History.md, README.md, bin/juice, client.js, lib/property.js, lib/selector.js, lib/utils.js, package.json, test/cases/juice-content/font-face-preserve.json, test/cases/juice-content/media-preserve.json, test/cli.js, test/juice.test.js
fixes #210 
resolves #190 
Notes on breaking changes:
- The specificity fixes in here should be minor or unnoticed for most users
- The upgraded web-resource-inliner will inline small SVGs by default, that can be disabled/adjusted through options. See https://www.npmjs.com/package/web-resource-inliner
- The changes to several of the default values might be undesirable for some use cases, so you may want to change these explicitly to `false` in the options for preserveMediaQueries, preserveFontFaces, insertPreservedExtraCss, applyWidthAttributes, applyHeightAttributes, applyAttributesTableElements. There were all added in the 1.x lifetime and initially set to `false` to avoid breaking changes, but for most cases, particularly emails, these should usually all be set to true. If inlining …
=> specificity fixes, dep updates, changes to option defaults, 2.0

lib/cli.js, test/cli.js
Added this to enable `xmlMode` for batch jobs on SVG documents.  Perhaps it's useful?
=> Expose `--xml-mode` in cli

.gitignore, CONTRIBUTING.md, juice.d.ts, package.json, test/typescript/cheerio.d.ts, test/typescript/juice-tests.ts
* Add `juice.d.ts` file
* Add `juice-tests.ts` file where whole API is used
* Add `types` entry to `package.json` pointing to the definitions file
* Add `typescript` devDependency and `@types/cheerio` dependency, since `juice` relies on `cheerio` library.
* Add note to `CONTRIBUTING.md`
* Is the location for `juice-tests.ts` OK? (`tests/typescript/juice-tests.ts`)
* Is the location for `juice.d.ts` OK? (project root)
=> Add TypeScript type definitions

package.json
The `0.20.0` version of Cheerio you depend on has a typo bug which makes it unimportable via its `index.js`. This has been fixed in [this commit](https://github.com/cheeriojs/cheerio/commit/7b59afbc7a6aa39376021593e011bf718350bcb4) and released in their `0.21.0` release. 
Unfortunately, Juice is hard depended on that old version. This is totally breaking our application right now but using the new version of Cheerio fixes it.
=> Allow newer versions of Cheerio, current one is broken.

juice.d.ts, test/typescript/juice-tests.ts
Since there is a new API in `v4.*`, I've updated the TypeScript type definitions file with the new API.
* Add `juice.codeBlocks` option to type definitions
* Add `juice.codeBlocks` usage to `juice-tests.ts`
* Sort `juice` options alphabetically in type definitions file
=> Add juice.codeBlocks to TypeScript type definitions

lib/cheerio.js
Hello guys,
Currently, the code contains ES6 lambda usage. Because of this, while using a bundler (e.g. Webpack) it's required to use "babel" for this particular lib only. Usually it's not required, so it would be good not to expose "node_modules" to "babel" at all. 
Since the app already uses anonymous functions, there should not be any problems with the proposed change.
=> Remove ES6 lambda feature occurrences

lib/utils.js, test/juice.test.js
Per https://github.com/Automattic/juice/issues/255, since `utils.getPreservedText` iterates over the rules in reverse order and pushes preserved items onto an array, the order of those preserved items is flipped. This causes CSS precedence issues in the final output.
We move from `Array.push` to `Array.unshift` for the preserved text, retaining the source order.
=> Retain the original order of preserved text. Fixes #255.

juice.d.ts, test/typescript/juice-tests.ts
The typing was a bit off for codeBlocks which made this option difficult to use with Typescript. It was expecting a single value like `juice.codeBlocks = {start: '{{', end: '}}'}` rather than the actual format, `juice.codeBlocks.HBS = {start: '{{', end: '}}'}`.
=> Fixed typing of codeBlocks to match documentation

lib/inline.js, test/cases/juice-content/table-attr.html, test/cases/juice-content/table-attr.out
Example:
```html
<style>
td { background-image: url("test.png"); }
</style>
<td>Foobar</td>
```
Without this fix results in broken HTML:
```html
<style>
td { background-image: url("test.png"); }
</style>
<td style="background-image: url('test.png');" background="url(" test.png")"="">Foobar</td>
```
After fix:
```html
<style>
td { background-image: url("test.png"); }
</style>
<td style="background-image: url('test.png');" background="url('test.png')">Foobar</td>
```
=> Bugfix: double quotes in table style attributes

README.md
Hi, I added this project https://github.com/notifme/notifme-template to "Projects using juice" section. It's a subproject of https://github.com/notifme/notifme-sdk
=> Add notifme-template to "Projects using juice" in README

lib/cheerio.js, test/cases/ejs-unterminated.css, test/cases/ejs-unterminated.html, test/cases/ejs-unterminated.out, test/cases/hbs-unterminated.css, test/cases/hbs-unterminated.html, test/cases/hbs-unterminated.out
The nested quantifier used in the encodeCodeBlocks regex can
catastrophically backtrack when it encounters unterminated ejs or hbs
tags. Fixes #260
=> Use regex that does not catastrophically backtrack

juice.d.ts, test/typescript/juice-tests.ts
The current TypeScript definitions disallow a use case that I think is intended to be used.  Right now when applying web-resources-inliner options, the code defaults the value for `fileContent`
see `juice/index.js:55`:
```
function inlineExternal(html, inlineOptions, callback) {
var options = utils.extend({fileContent: html}, inlineOptions);
inline.html(options, callback);
}
```
As written currently, the TS interface for these options makes `fileContent` required.  That means that the defaulting behavior above is only used if no other options are set.  However if I want to do something like disable image inlining, i'd have to pass the `fileContent` option, meaning I'd be passing the html value twice in the same call.
This PR makes the `fileContent` option optional, so if it is not …
=> update TS definition to allow for optional fileContent option

lib/cheerio.js
Allow the variable `codeBlockLookup` to be dropped out of scope so that each time `juice` is run it does not accrue more code block lookups (which is a memory leak).
=> Fix memory leak in cheerio code block encode/decode

index.js
When using TypeScript to load `juice`, the current import does not work properly because it implies the extension `.json`. Explicitly adding the extension makes the library more portable.
closes #303
=> Include extension when requiring package.json

README.md, juice.d.ts, lib/cli.js, lib/inline.js, lib/utils.js, test/cases/juice-content/pseudo-selector-preserve.html, test/cases/juice-content/pseudo-selector-preserve.json, test/cases/juice-content/pseudo-selector-preserve.out
This adds a new  `preservePseudos` option. 
It preserves all rules containing pseudo selectors defined in `ignoredPseudos` within `<style></style>` tags as a refinement when `removeStyleTags` is `true`. Other styles are removed. Defaults to `true`.
---
Note: I've decided to go for a boolean option instead of something like an array, since there already is `ignoredPseudos` we can defined them in. Please let me know if this is ok. Thanks!
=> Preserve pseudos

lib/inline.js, test/cases/juice-content/height-attr.html, test/cases/juice-content/height-attr.out, test/cases/juice-content/width-attr.html, test/cases/juice-content/width-attr.out
Because of a box model bug in older Android versions (I believe stripping doctype), the easiest way to make columns properly stack in a responsive design is to use `<th>` instead of `<td>`.
For those using `<th>`, this pull request covers them out-of-the-box, as you always need to declare attribute widths/heights on table cells, for Outlook.
=> Add TH to list of elements that can receive width and height attributes

lib/inline.js
Just noticed there was a duplicate `'TD'` in `juiceClient.tableElements`.
=> Remove duplicate TD in juiceClient.tableElements

package.json
Bumps the mensch CSS parser to fix a memory leak in the stringify function of version 0.3.3.
See https://github.com/brettstimmerman/mensch/issues/25 for more information.
=> deps: bump mensch to fix mem leak

package.json
It's only used in test/cli.js module.
=> Move cross-spawn to dev dependencies

index.js, lib/cheerio.js, lib/utils.js
No need to implement this utility or choose the library in every
project.
=> Replace custom extend utility with native Object.assign

juice.d.ts, lib/cli.js, test/cli.js, test/typescript/juice-tests.ts
I do not see these options are implemented in web-resource-inliner
or juice.
=> Drop unused cssmin and uglify options from cli

bin/juice, package-lock.json, package.json
deep-extend is only used to handle one nested options object.
In this diff I replaced dependency with native Object.assign and handled
"webResources" as special case similar to special case in cli options
definitions.
=> Replace deep-extend with nested Object.assign

lib/inline.js, test/run.js, test/typescript/juice-tests.ts
We need to inline very large svgs (~100MB). Cheerio uses `parse5` by default, which is very slow and memory intensive for files of this size. Cheerio also supports (and ships with) `htmlparser2`, which has a slightly different API. This PR makes using `htmlparser2` possible by detecting which API is present.
I'm not an expert on this and I'm not sure if the test I wrote is complete enough, but from my tests the only important API difference was that `el.childNodes[0].nodeValue` in `parse5` corresponds to `el.children[0].data` in `htmlparser2`.
=> Support htmlparser2

lib/inline.js, test/cases/juice-content/important.html, test/cases/juice-content/important.out
This fixes https://github.com/Automattic/juice/issues/356, which I encountered when cleaning up a marketing email today. I moved the regex to remove `!important` into a dedicated function, then referenced that function in a couple of places where the attributes are added.
This is my first commit to this repo, but I've tried to match the existing style and even added a test! Let me know if I'm missing anything. :)
=> Fix !important added to table attributes

lib/inline.js, package-lock.json, package.json, test/run.js
hi contributors
There is a vulnerability in `css-what` package https://avd.aquasec.com/nvd/cve-2021-33587/ which use by `"cheerio": "^1.0.0-rc.3"` of your dependency. 
cheerio has done this new release for the update & juice need to update to that version to avoid the vulnerable package
https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0-rc.10
Please help check whether there are any breaking changes here, if not can you please do a new release?
=> CVE-2021-33587 dependency update

lib/inline.js, test/cases/juice-content/height-attr.html, test/cases/juice-content/height-attr.out, test/cases/juice-content/width-attr.html, test/cases/juice-content/width-attr.out
**What?**
Add support for `auto` as value for `height`/`width` properties
**Why?**
Scenarios like Outllook Windows support setting `width` only as attribute but resetting to `auto` is not possible with the current behavior, this allows to add `width="auto"` when applicable.
```
> mocha --reporter spec && npm run test-typescript
✓ cli parses options
✓ cli no css (502ms)
✓ cli css included (307ms)
✓ cli options included (283ms)
✓ cli supports codeBlock (281ms)
✓ extracting selectors
✓ selector specificity comparison
✓ selector specificity calculator
✓ property comparison based on selector specificity
✓ property toString
✓ parse simple css into a object structure
✓ parse complex css into a object structure
✓ test excludedProperties setting
✓ test juice
✓ test consecutive important rules
✓ …
```
=> Add support for 'auto' as value for height/width properties

client.js, index.js
Hello!
**Summary**
Set `juiceClient.codeBlocks = cheerio.codeBlocks` in `/lib/client.js` instead of `/index.js` so that it gets emitted by webpack. I also removed some assignments in `/index.js` that should already exist because `juice = juiceClient`.
**Motivation**
Webpack does not emit `juice.codeBlocks = juiceClient.codeBlocks` (or any of the other assignments in `/index.js`). This breaks `codeBlocks` when using juice in the browser via `mjml-browser` (see https://github.com/mjmlio/mjml/issues/2653). Assigning `codeBlocks` in `/lib/client.js` instead of `/index.js` fixes the issue when testing locally via `npm link`.
Thanks for considering my PR!
=> juice.codeBlocks does not get removed by webpack

lib/inline.js, test/cases/juice-content/counter-reset.html, test/cases/juice-content/counter-reset.json, test/cases/juice-content/counter-reset.out
An error is thrown in `resetCounter` when adding an `counter-reset` inline style to an element in combination with a different style (e.g., in head).
```
1) juice-content/counter-reset:
Uncaught TypeError: Cannot set properties of undefined (setting 'li')
at resetCounter (lib/inline.js:167:40)
at addProps (lib/inline.js:198:15)
at Element.<anonymous> (lib/inline.js:146:11)
at LoadedCheerio.each (node_modules/cheerio/lib/api/traversing.js:519:26)
at handleRule (lib/inline.js:120:9)
at Array.forEach (<anonymous>)
at inlineDocument (lib/inline.js:36:9)
at juiceDocument (lib/inline.js:459:3)
at module.exports (lib/cheerio.js:61:22)
at onInline (index.js:63:7)
at /Users/.../juice/node_modules/web-resource-inliner/src/html.js:281:13
```
This error is caused by the fact that the `addProps` …
=> Fixed counter-reset not working in combination with inline styles

README.md, juice.d.ts, lib/cli.js, lib/inline.js, lib/utils.js, lib/variables.js, package-lock.json, test/cases/css-variables.css, test/cases/css-variables.html, test/cases/css-variables.json, test/cases/css-variables.out, test/cases/juice-content/pseudo-elements.json, test/cli.js, test/run.js
Resolves 
```html
<style>
:root{
--color:blue;
}
p{
color:var(--color);
}
</style>
<p>woot</p>
```
to
```html
<p style="color: blue;">woot</p>
```
See also #312
=> Resolve CSS variables

package-lock.json, package.json
Fixes issues with breaking changes from `cheerio@1.0.0` until it's handled somehow upstream.
See [discussion](https://github.com/cheeriojs/cheerio/issues/3993) for more info.
=> fix: pin cheerio to latest rc.12

README.md, juice.d.ts, lib/cli.js, lib/inline.js, package-lock.json, package.json, test/cli.js, test/juice.test.js
Fix #482 
This PR adds an option to decode HTML entities in the style attribute before it is handed off to mensch for parsing. The problem is that although HTML entities are valid in `style` attribute values, they are not valid in CSS strings, resulting in a mensch parse that contains invalid properties/values, and ultimately causes juice to fail.
=> Fix #482: "Error when encoded quotes are used in html attribute"

package-lock.json, package.json
`cheerio@1.1.x` introduced [a breaking change](https://github.com/cheeriojs/cheerio/pull/4689/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) in the form of requiring Node 20+ in a patch release.
This PR temporarily pins `cheerio` down to `v1.0.0` which was the last version to support Node 18. 
If  `cheerio` reverts this breaking change and releases it separately as a major version, we will then resume depending on the latest minor release.
=> build: pin cheerio version to 1.1.0
