History.md
package.json

@rauchg should be prepped for release. Hopefully I got all the changes in well enough.

1.0.0 history and package.json

---

lib/juice.js
package.json
test/cases/juice-content/relative-url.html
test/cases/juice-content/relative-url.json
test/cases/juice-content/relative-url.out
test/cases/php.css
test/cases/php.html
test/cases/php.out
test/cases/templates.html
test/cases/templates.out

add tests to cover #57 
fixes #105 
fixes #104 
Patches a few new issues, including pointing at a new version of web-resource-inliner
@rauchg if you get a chance to look it would be appreciated.

test case for php

---

bin/juice

Update bin/juice to use `juice.juiceFile`

---

History.md
README.md
package.json

- fixes #117 
- bump package version

v1.1.0 release updates

---

index.js
package.json

So we talked about adding the `main`property to the `package.json` in https://github.com/Automattic/juice/pull/119.

Add main field and delete index.js ref https://github.com/Automattic/juice/pull/119

---

lib/juice.js
lib/utils.js

I use this patch to inline some css into svg.

Support for xml

---

.travis.yml
lib/juice.js
lib/property.js
lib/selector.js
lib/utils.js

Trying to fix #133 and did a proper linting pass.
There are no feature changes here and all tests are passing.

use strict / linting

---

History.md
README.md
lib/juice.js
test/cases/juice-content/important.html
test/cases/juice-content/important.json
test/cases/juice-content/important.out

add preserveImportant option

---

package.json

bump cheerio version

---

History.md
README.md
lib/juice.js
lib/utils.js
test/cases/juice-content/font-face-preserve.html
test/cases/juice-content/font-face-preserve.json
test/cases/juice-content/font-face-preserve.out

related to #132 
This makes it easy to preserve `@font-face` without having to wrap it in `@media`

Add option preserveFontFaces

---

lib/juice.js

fixes #162 
@maghidini what do you think of this resolution?

fix undefined property error, issue #162

---

README.md
lib/juice.js
test/cases/juice-content/height-attr.html
test/cases/juice-content/height-attr.json
test/cases/juice-content/height-attr.out

Implement inlining of height attributes.

---

bin/juice

avoid mutating the original

---

client.js
test/cases/juice-content/important.html
test/cases/juice-content/important.out

Fix #185 but maybe not very clean. At least that make the issue more explicit :-)

Preserve inlined `!important`

---

History.md
package.json
test/cli.js

Replace deprecated dep `win-spawn` with `cross-spawn-async`

---

.jscsrc
CONTRIBUTING.md
History.md
bin/juice
client.js
index.js
lib/cli.js
lib/property.js
lib/selector.js
lib/utils.js
package.json
test/cases/integration.css
test/cli.js
test/juice.test.js
test/run.js
test/test.js

JSCS, specificity of !important rules, 1.11 release

---

package.json

#233 Mensch 0.3.3 now in npm thanks to @bago

update mensch dependence

---

README.md

https://github.com/kriasoft/nodejs-api-starter
https://github.com/kriasoft/nodejs-api-starter/tree/master/src/emails

Add nodejs-api-starter, a project using Juice

---

README.md

fix(readme): use svg badges

---

package-lock.json
package.json

upgrade wri dep, release 4.1.2

---

lib/cli.js
test/cli.js

Add —preserve-important option to the CLI

---

History.md
lib/cheerio.js
package.json
test/cases/ejs.html
test/cases/ejs.out

Fix code blocks encode/decode so cheerio doesn't mulch them if they are tag attributes

---

README.md

I contributed to Mensch and the PR to make Juice use Mensch so to be able to use both of them in Mosaico.

Added Mosaico email editor reference

---

package-lock.json
package.json

Sounds like the build with npm 5+ is broken since 4.1.1:
https://travis-ci.org/Automattic/juice/builds
I simply did an "npm update && npm install" and updating the package-lock everything started building again.

package-lock was outdated and npm install failed

---

lib/inline.js
test/cases/juice-content/prevent-css-gradient-in-attribute-issue319.html
test/cases/juice-content/prevent-css-gradient-in-attribute-issue319.json
test/cases/juice-content/prevent-css-gradient-in-attribute-issue319.out

Prevent css gradient in attribute

---

PROJECTS.md

[Grunt email workflow](https://github.com/leemunroe/grunt-email-workflow) makes use of Juice for inlining as one of the many email related tasks. Great resource 🙌

Add Grunt email workflow to projects list

---

PROJECTS.md

Updated repo URL and description.

Update Maizzle details.

---

lib/inline.js

Fixes https://github.com/Automattic/juice/issues/332

Fix dangling comma in css selector

---

lib/cheerio.js
package-lock.json
package.json

This version of cheerio already 1 year published with latest tag.
Here are changes
https://github.com/cheeriojs/cheerio/blob/v1.0.0-rc.3/History.md#100-rc2--2017-07-02

Upgrade to cheerio v1

---

bin/juice
package-lock.json
package.json

Fixed args length check. Anything else works as before.

Upgrade commander

---

package.json

To prevent publishing wrong files.

Publish only necessary files in package

---

.travis.yml
package-lock.json
package.json

Very small package now
https://packagephobia.com/result?p=web-resource-inliner@5.0.0
Requires node 10+

Upgrade web-resource-inliner

---

lib/inline.js
lib/numbers.js
package.json
test/cases/juice-content/pseudo-elements.html
test/cases/juice-content/pseudo-elements.out

Adds support for `<var>` `<attr>` `<counter>` in content attributes for pseudo-elements. Also adds the possibility of defining counter-reset and counter-increment in styles.
Fixes #256.

Add support for counters and multiple values in pseudo-elements

---

package.json

Fixed cheerio version to stop breaking changes in its latest version `1.0.0-rc.11`

Fixed cheerio version

---

.github/workflows/nodejs.yml
.travis.yml

This PR switches the CI from Travis to GitHub Actions.
I've preserved the same Node versions, but let me know if I should add/remove anything. Thanks!

ci: add github workflow
